package com.ecommerce.auth_service.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents an authenticated user in the system.
 * This entity is used for managing login credentials and roles.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class AuthUser {

    /**
     * Primary key for the AuthUser entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique email address of the user.
     * Used as the username for authentication.
     */
    @Column(unique = true)
    private String email;

    /**
     * Encrypted password for authentication.
     * Should never be stored in plain text.
     */
    private String password;

    /**
     * Role of the user (e.g., ROLE_USER, ROLE_ADMIN).
     * Used for authorization and access control.
     */
    private String role;
}
